package chav1961.jcw.interfaces;

public enum TokenSort {
	WHITESPACE,
	COMMENT,
	DOCCONTENT,
	KEYWORD,
	RESERVEDKEYWORD,
	PREPROCESSOR,
	ANNOTATION,
	PUNCTUATION,
	OPERATORS,
	NUMCONSTANT,
	TEXTCONSTANT,
	SPECIALCONSTANT,
	IDENTIFIER,
	UNCLASSIFIED
}
